apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: arango
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: arango
    spec:
      containers:
        - name: arango
          image: arangodb/arangodb:3.0.4
          ports:
            - containerPort: 8529
          env:
            - name: ARANGO_RANDOM_ROOT_PASSWORD
              value: "1"
